services:
  - name: service1
    readinessProbe:
      httpGet:
        path: /health
        port: 8080
    livenessProbe:
      tcpSocket:
        port: 8080
  - name: service2
    readinessProbe:
      exec:
        command: ["ls", "/app"]
    livenessProbe:
      httpGet:
        path: /api/health
        port: 80
  - name: service3
    readinessProbe: null
    livenessProbe: null

